# 时光信笺 - 开发环境配置
spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timecapsule?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: abc123456  # 建议使用环境变量

    # Druid连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # Druid监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # Redis配置
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
  timeout: 6000ms
  lettuce:
    pool:
      max-active: 8
      max-wait: -1ms
      max-idle: 8
      min-idle: 0

  # Security配置（开发环境）
  security:
    user:
      name: admin
      password: admin123

# Redisson配置
redisson:
  # 单节点配置
  single-server-config:
    address: 127.0.0.1:6379
    password:
    database: 0
  # 线程池配置
  threads: 16
  netty-threads: 32
  # 编解码器 - 使用字符串类名而不是标签
  codec: org.redisson.codec.JsonJacksonCodec
  # 传输模式
  transport-mode: "NIO"

# 开发环境特殊配置
app:
  # 开发环境关闭某些安全限制
  security:
    permit-all-urls:
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /doc.html
      - /webjars/**
      - /druid/**
      - /actuator/**

  # 开发环境启用调试模式
  debug:
    enabled: true
    show-sql: true

# 日志级别（开发环境）
logging:
  level:
    com.timecapsule: debug
    org.springframework.security: debug
    com.baomidou.mybatisplus: debug